spring:
  jpa:
    properties:
      hibernate:
        show_sql: ${JPA_SHOW_SQL:false}
        format_sql: ${JPA_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true

server:
  port: ${APP_SERVER_PORT:3000}
  address: ${APP_SERVER_HOST:localhost}


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptos:
          - com.dextra.hp.config.FeignInterceptor

logging:
  level:
    root: ${LOG_LEVEL:INFO}
