server:
  port: ${APP_SERVER_PORT:3000}
  address: ${APP_SERVER_HOST:localhost}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptos:
          - com.dextra.hp.config.FeignInterceptor

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:900722}
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true